"""Preregistered drift corpus.

Generated AFTER the detection floor was committed (`a038a2e`). Semantic variant
magnitudes are functions of that committed floor, not free choices:

    S-invisible  = 0.15 x floor   (single period)
    S-obvious    = 2.50 x floor   (single period)
    S-creep      = 0.15 x floor   (sustained over every evaluation period)

Every variant carries a ground-truth label. Detectability is never used as a
labelling criterion -- variants are labelled by what changed, per the
contamination rule in ../operating_procedure.md 2.2.

Written fresh. See BUILD_NOTES.md: nothing from Data-tool was ported except the
rename vocabulary, as data.
"""

from __future__ import annotations

import argparse
import io
import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Callable

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
ARTIFACTS = ROOT / "artifacts"
SPEC = ROOT / "spec"
MEASURE = "amount"
EVAL_START = 12          # held-out periods begin here
SINGLE_PERIOD_INDEX = 18  # where single-period semantic variants are injected


@dataclass
class Variant:
    name: str
    drift_class: str                     # none | cosmetic | structural | semantic
    story: str
    fn: Callable[[pd.DataFrame], pd.DataFrame]
    apply_at: str = "all"                # all | single
    # Ground truth: would running the procedure on this variant produce the SAME
    # canonical output as on unchanged data? Determined by construction, never by
    # whether the harness detects it (operating_procedure.md 2.2).
    output_equivalent: bool = False
    meta: dict = field(default_factory=dict)


# ---------------------------------------------------------------- cosmetic


def _load_vocab() -> dict:
    return json.loads((SPEC / "rename_vocabulary.json").read_text(encoding="utf-8"))


def _rename_map() -> dict[str, str]:
    """Pick a realistic provider-style rename from the copied vocabulary."""
    v = _load_vocab()
    syn = v["synonyms"]
    col = v["canonical_to_baseline_column"]
    # Deterministic pick: a mid-list term, so it is not the trivially-equal first entry.
    return {col[canon]: syn[canon][len(syn[canon]) // 2] for canon in syn}


def cos_rename(df: pd.DataFrame) -> pd.DataFrame:
    return df.rename(columns=_rename_map())


def cos_reorder(df: pd.DataFrame) -> pd.DataFrame:
    return df[list(reversed(df.columns))]


def cos_decimal_comma(df: pd.DataFrame) -> pd.DataFrame:
    out = df.copy()
    out[MEASURE] = out[MEASURE].map(lambda x: f"{x:,.2f}".replace(",", " ").replace(".", ","))
    return out


def cos_case_whitespace(df: pd.DataFrame) -> pd.DataFrame:
    out = df.copy()
    out["article_sku"] = out["article_sku"].map(lambda s: f"  {s.lower()} ")
    return out


def cos_period_format(df: pd.DataFrame) -> pd.DataFrame:
    out = df.copy()
    out["report_period"] = out["report_period"].map(lambda p: f"{p[5:]}/{p[:4]}")
    return out


# -------------------------------------------------------------- structural


def str_insert_column(df: pd.DataFrame) -> pd.DataFrame:
    """The D1 trap: one extra column before the measure.

    A name-based contract fails this loudly. A positional mapper -- like
    Data-tool's filter_and_rename -- shifts every mapping and still succeeds.
    """
    out = df.copy()
    pos = list(out.columns).index(MEASURE)
    out.insert(pos, "discount_pct", 0.0)
    return out


def str_wide(df: pd.DataFrame) -> pd.DataFrame:
    return (
        df.pivot_table(index="article_sku", columns="report_period", values=MEASURE, aggfunc="sum")
        .reset_index()
    )


def str_grain_split(df: pd.DataFrame) -> pd.DataFrame:
    """Grain becomes per-invoice-line. Period total is PRESERVED exactly."""
    a, b = df.copy(), df.copy()
    a["quantity"] = (a["quantity"] // 2).clip(lower=0)
    b["quantity"] = b["quantity"] - a["quantity"]
    a[MEASURE] = (a[MEASURE] / 2).round(2)
    b[MEASURE] = (b[MEASURE] - a[MEASURE]).round(2)
    a["freight"] = (a["freight"] / 2).round(2)
    b["freight"] = (b["freight"] - a["freight"]).round(2)
    return pd.concat([a, b], ignore_index=True).sort_values(["article_sku"]).reset_index(drop=True)


def str_drop_column(df: pd.DataFrame) -> pd.DataFrame:
    return df.drop(columns=["freight"])


def str_header_offset(df: pd.DataFrame) -> pd.DataFrame:
    """Three banner rows prepended, then re-parsed with a default header row."""
    pad = "," * (len(df.columns) - 1)   # banner occupies column A only, as in a real export
    buf = io.StringIO()
    buf.write(f"Monthly sales export{pad}\n")
    buf.write(f"Generated by the provider ERP{pad}\n")
    buf.write(f"Headers start on row 4{pad}\n")
    df.to_csv(buf, index=False, lineterminator="\n")
    buf.seek(0)
    return pd.read_csv(buf)   # default header=0 -> the banner becomes the header row


# ---------------------------------------------------------------- semantic


def _semantic(shift_pct: float) -> Callable[[pd.DataFrame], pd.DataFrame]:
    """Redefine the measure to absorb a proportion of the freight component.

    Structure, grain, dtypes, column names and row counts are byte-identical.
    Only the meaning of `amount` changes. This is the N1 condition.
    """

    def apply(df: pd.DataFrame) -> pd.DataFrame:
        out = df.copy()
        total = out[MEASURE].sum()
        freight = out["freight"].sum()
        if freight <= 0:
            return out
        multiplier = (shift_pct * total) / freight
        out[MEASURE] = (out[MEASURE] + out["freight"] * multiplier).round(2)
        return out

    return apply


# ------------------------------------------------------------------ corpus


def build_variants(floor_pct: float) -> list[Variant]:
    f = floor_pct / 100.0
    s_invisible, s_obvious, s_creep = 0.15 * f, 2.50 * f, 0.15 * f

    return [
        Variant("C0_unchanged", "none", "control, no change", lambda d: d,
                output_equivalent=True),

        Variant("COS_rename", "cosmetic",
                "headers renamed to real provider vocabulary", cos_rename),
        Variant("COS_reorder", "cosmetic", "columns reversed", cos_reorder,
                output_equivalent=True),   # name-based access is order-independent
        Variant("COS_decimal_comma", "cosmetic",
                "measure written as '1 234,56'", cos_decimal_comma),
        Variant("COS_case_whitespace", "cosmetic",
                "sku lowercased and padded", cos_case_whitespace),
        Variant("COS_period_format", "cosmetic",
                "period written as MM/YYYY", cos_period_format),

        Variant("STR_insert_column", "structural",
                "extra column inserted before the measure (D1 trap)", str_insert_column),
        Variant("STR_wide", "structural", "long reshaped to wide", str_wide),
        Variant("STR_grain_split", "structural",
                "grain becomes per-invoice-line; period total preserved", str_grain_split),
        Variant("STR_drop_column", "structural", "freight column removed", str_drop_column),
        Variant("STR_header_offset", "structural",
                "three banner rows prepended", str_header_offset),

        Variant("SEM_invisible", "semantic",
                f"measure redefined; shift = 0.15 x floor = {s_invisible*100:.3f}%",
                _semantic(s_invisible), apply_at="single",
                meta={"target_shift_pct": round(s_invisible * 100, 4), "floor_multiple": 0.15}),
        Variant("SEM_obvious", "semantic",
                f"measure redefined; shift = 2.50 x floor = {s_obvious*100:.3f}%",
                _semantic(s_obvious), apply_at="single",
                meta={"target_shift_pct": round(s_obvious * 100, 4), "floor_multiple": 2.50}),
        Variant("SEM_creep", "semantic",
                f"measure redefined; shift = 0.15 x floor sustained from period {EVAL_START}",
                _semantic(s_creep), apply_at="all",
                meta={"target_shift_pct": round(s_creep * 100, 4), "floor_multiple": 0.15,
                      "sustained": True}),
    ]


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", type=Path, default=ARTIFACTS / "drift_corpus")
    args = ap.parse_args()

    floor = json.loads((ARTIFACTS / "detection_floor.json").read_text(encoding="utf-8"))
    if not floor.get("declared_before_drift_corpus"):
        raise SystemExit("Detection floor is not marked as declared pre-corpus. Aborting.")

    df = pd.read_csv(ARTIFACTS / "baseline_history.csv")
    periods = sorted(df["report_period"].unique())
    variants = build_variants(floor["min_detectable_shift_pct"])

    args.out.mkdir(parents=True, exist_ok=True)
    index = []

    for v in variants:
        for t in range(EVAL_START, len(periods)):
            period = periods[t]
            src = df[df["report_period"] == period].reset_index(drop=True)
            touched = v.apply_at == "all" or t == SINGLE_PERIOD_INDEX
            out = v.fn(src) if touched else src.copy()
            path = args.out / f"{v.name}__{period}.csv"
            out.to_csv(path, index=False, lineterminator="\n")
            index.append(
                {
                    "variant": v.name,
                    "drift_class": v.drift_class,
                    "period": period,
                    "period_index": t,
                    "modified": bool(touched),
                    "file": path.name,
                }
            )

    manifest = {
        "generated_after_floor_commit": floor["baseline_commit"],
        "floor_used": {
            "min_detectable_shift_pct": floor["min_detectable_shift_pct"],
            "sustained_min_detectable_shift_pct": floor["sustained_min_detectable_shift_pct"],
        },
        "eval_start_index": EVAL_START,
        "single_period_index": SINGLE_PERIOD_INDEX,
        "labelling_rule": (
            "Variants are labelled by WHAT CHANGED, never by what would have been detected "
            "(operating_procedure.md 2.2)."
        ),
        "rename_vocabulary_source": "Data-tool config.yaml synonyms, data only",
        "variants": [
            {"name": v.name, "drift_class": v.drift_class, "story": v.story,
             "apply_at": v.apply_at, "output_equivalent": v.output_equivalent, **v.meta}
            for v in variants
        ],
        "files": index,
    }
    (ARTIFACTS / "drift_corpus_manifest.json").write_text(
        json.dumps(manifest, indent=2) + "\n", encoding="utf-8"
    )

    print(f"variants : {len(variants)}")
    print(f"files    : {len(index)}")
    for v in variants:
        if v.drift_class == "semantic":
            print(f"  {v.name:18s} target shift {v.meta['target_shift_pct']:.3f}% "
                  f"({v.meta['floor_multiple']}x floor)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
