#!/usr/bin/env python3
"""W1-E fidelity gate -- reported INDEPENDENTLY of the structural grader.

Runs the FROZEN fidelity checker (`work_interface/fidelity/fidelity_check.py`,
pinned by sha256 to its state at 70e1484) over each M run's artifact.

    FIDELITY PASS = zero findings from FID-1..FID-6 within the checker's
                    already-declared scope.

No artifact-specific expectations exist for W1-E. This is the first BLIND
application of the instrument: the corpus has not been inspected, and the gate is
a plain zero-findings test rather than a comparison against a hand-derived table.

The checker's declared scope is unchanged and is NOT re-litigated here:
rows 0/1 carry slot-level FID-1; rows 4/5 carry FID-5 only (v0 gives their
output slots no provenance machinery); row 3 participates in attribution but has
no bound v0 decision slot; rows 6/7 are not delivered and are out of scope, so
`on_non_numeric` remains an observed divergence, never a finding.

FID-1 remains a PROPOSED fidelity invariant, not structural-validator law.

    python work_interface/w1e/fidelity_gate.py

Read-only: never edits, repairs or moves an artifact.
"""
from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
WORK_INTERFACE = HERE.parent
FIDELITY_DIR = WORK_INTERFACE / "fidelity"

# The frozen instrument, pinned. If this hash moves, the gate refuses to run:
# a fidelity verdict is only meaningful against a declared instrument.
FROZEN_FIDELITY_CHECK_SHA256 = (
    "11984c096b8fd74f40549d17f9300dc732f3dbe1d4e1112f3dc0f412036b41d4")

RUNS = ["M1", "M2", "M3"]
ARTIFACT = "work_definition.json"


def main() -> int:
    checker = FIDELITY_DIR / "fidelity_check.py"
    if not checker.is_file():
        print(f"GATE ERROR: frozen checker not found at {checker}", file=sys.stderr)
        return 2
    digest = hashlib.sha256(checker.read_bytes()).hexdigest()
    if digest != FROZEN_FIDELITY_CHECK_SHA256:
        print(f"GATE ERROR: fidelity_check.py has drifted\n"
              f"  expected {FROZEN_FIDELITY_CHECK_SHA256}\n"
              f"  got      {digest}", file=sys.stderr)
        return 2

    sys.path.insert(0, str(FIDELITY_DIR))
    import fidelity_check as F  # noqa: E402
    canon = F.canonical_rows()

    records, total = [], 0
    for run in RUNS:
        p = HERE / "runs" / run / ARTIFACT
        if not p.is_file():
            records.append({"run": run, "status": "NO_ARTIFACT", "findings": [],
                            "confirmations": {}})
            continue
        try:
            art = json.loads(p.read_text(encoding="utf-8"))
        except Exception as e:
            records.append({"run": run, "status": "UNPARSEABLE_JSON",
                            "findings": [], "confirmations": {},
                            "error": f"{type(e).__name__}: {e}"})
            continue
        res = F.check_artifact(art, canon)
        total += len(res["findings"])
        records.append({
            "run": run,
            "status": "FIDELITY PASS" if not res["findings"] else "FIDELITY FINDINGS",
            "findings": res["findings"],
            "confirmations": {k: {"rows": v["rows"], "verdict": v["verdict"],
                                  "subreason": v["subreason"]}
                              for k, v in res["confirmations"].items()},
            "artifact_sha256": hashlib.sha256(p.read_bytes()).hexdigest(),
        })

    graded = [r for r in records if r["status"].startswith("FIDELITY")]
    passing = [r for r in graded if r["status"] == "FIDELITY PASS"]

    lines = ["# W1-E fidelity results", "",
             "Generated by `work_interface/w1e/fidelity_gate.py`. Read-only.",
             "Reported INDEPENDENTLY of the structural grader.", "",
             f"- frozen checker sha256: `{FROZEN_FIDELITY_CHECK_SHA256}`",
             "- FIDELITY PASS = zero findings within the checker's declared scope",
             "- FID-1 is a proposed fidelity invariant, not structural-validator law",
             "", "## Per-run", "",
             "| run | fidelity | findings | artifact sha256 |", "|---|---|---|---|"]
    for r in records:
        lines.append(f"| {r['run']} | **{r['status']}** | {len(r['findings'])} | "
                     f"`{r.get('artifact_sha256','-')[:12]}` |")
    lines += ["", "## Detail", ""]
    for r in records:
        lines.append(f"### {r['run']} — {r['status']}")
        lines.append("")
        for cid, v in (r["confirmations"] or {}).items():
            sub = f" [{v['subreason']}]" if v["subreason"] else ""
            lines.append(f"- confirmation `{cid}` rows={v['rows']} "
                         f"{v['verdict']}{sub}")
        for f in r["findings"]:
            lines.append(f"- `{f['finding']}` @ `{f['where']}` — {f['detail']}")
        if not r["findings"] and r["confirmations"]:
            lines.append("- no findings")
        lines.append("")
    lines += ["## Fidelity rate", "",
              f"**{len(passing)}/{len(RUNS)} FIDELITY PASS** "
              f"({total} finding(s) across graded runs).", ""]

    md = "\n".join(lines)
    (HERE / "FIDELITY.md").write_text(md, encoding="utf-8")
    (HERE / "FIDELITY.json").write_text(
        json.dumps({"frozen_fidelity_check_sha256": FROZEN_FIDELITY_CHECK_SHA256,
                    "runs": records}, indent=2, ensure_ascii=False),
        encoding="utf-8")
    print(md)
    print("-" * 60)
    print(f"Wrote {HERE / 'FIDELITY.md'} and {HERE / 'FIDELITY.json'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
