#!/usr/bin/env python3
"""W1-J PRIMARY MEASURE — per-row confirmation preservation vs delivery position.

**Overall FIDELITY PASS is deliberately not the primary result.** It collapses
six independent observations into one bit, and the question here is *which* rows
survive, not how many runs are clean.

For every run, every canonical row is reported independently:

```text
row   delivery_position   provenance_slot   preservation
```

with `preservation` one of:

```text
EXACT_INDIVIDUAL  one confirmation carries this row, and only this row
BUNDLED           a confirmation carries this row together with others
NONVERBATIM       a confirmation carries this row but not verbatim
ABSENT            no confirmation carries this row
```

and one mechanical descriptor per run, a measurement and **not a gate**:

```text
preserved_prefix_length  how many rows, counting from the START OF DELIVERY,
                         are EXACT_INDIVIDUAL before the first that is not
```

The prefix is computed over **delivery order**, so it is comparable across packs
that deliver the rows in different sequences. That is the whole point: if W1-J
preserves rows 5,4,3 and loses 2,1,0, the *identity* of the preserved rows has
changed while the prefix shape survived.

W1-H is included for comparison as a **cross-pack differential**, not as a
simultaneously randomized arm.

    python work_interface/w1j/preservation_report.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
WI = HERE.parent
sys.path.insert(0, str(WI / "fidelity"))
sys.path.insert(0, str(WI / "w1b" / "harness"))
sys.path.insert(0, str(HERE / "harness"))
import fidelity_check as F  # noqa: E402
import block_harness as B  # noqa: E402
import run_batch as RB  # noqa: E402

EXACT_INDIVIDUAL = "EXACT_INDIVIDUAL"
BUNDLED = "BUNDLED"
NONVERBATIM = "NONVERBATIM"
ABSENT = "ABSENT"

RUNS = ["Q1", "Q2", "Q3"]
CONTROL = ("W1-H", WI / "w1h", ["P1", "P2", "P3"],
           tuple(B.MANDATED_ROWS))          # delivered 0..5
TREATMENT = ("W1-J", HERE, RUNS, RB.DELIVERY_ORDER)   # delivered 5..0

# Read from the v0 schema, not inferred: _check_basis() is called at exactly two
# sites in work_definition.py -- body.match_on and body.compare[<field>].
PROVENANCE_SLOT = {0: "YES", 1: "YES", 2: "NO", 3: "NO", 4: "NO", 5: "NO"}
ROW_LABEL = {0: "match key", 1: "compare", 2: "currency",
             3: "source of truth", 4: "report fields", 5: "context fields"}


def classify(artifact: Path, canon: dict[int, str]) -> dict[int, str]:
    res = F.check_artifact(json.loads(artifact.read_text(encoding="utf-8")),
                           canon)
    confs = res["confirmations"]
    out = {}
    for row in sorted(canon):
        carriers = [(cid, v) for cid, v in confs.items()
                    if row in (v.get("rows") or [])]
        if not carriers:
            out[row] = ABSENT
        elif any(len(v.get("rows") or []) > 1 for _, v in carriers):
            out[row] = BUNDLED
        elif carriers[0][1].get("verdict") != "normal" \
                or carriers[0][1].get("subreason"):
            out[row] = NONVERBATIM
        else:
            out[row] = EXACT_INDIVIDUAL
    return out


def prefix_length(cls: dict[int, str], order: tuple) -> int:
    n = 0
    for row in order:
        if cls.get(row) == EXACT_INDIVIDUAL:
            n += 1
        else:
            break
    return n


def collect(pack, root, runs, order):
    tbl = B.load_table_rows(RB.HUMAN_ANSWERS)
    canon = {i: tbl[i][1] for i in B.MANDATED_ROWS}
    out = []
    for run in runs:
        art = root / "runs" / run / "work_definition.json"
        if not art.is_file():
            out.append({"pack": pack, "run": run, "status": "NO_ARTIFACT",
                        "order": list(order)})
            continue
        cls = classify(art, canon)
        out.append({"pack": pack, "run": run, "status": "GRADED",
                    "order": list(order),
                    "rows": {str(k): v for k, v in cls.items()},
                    "preserved_prefix_length": prefix_length(cls, order)})
    return out


def main() -> int:
    control = collect(*CONTROL)
    treatment = collect(*TREATMENT)

    lines = ["# W1-J preservation results", "",
             "Generated by `work_interface/w1j/preservation_report.py`. "
             "Read-only.", "",
             "**Primary measure.** Overall FIDELITY PASS is deliberately not "
             "used as the result.", "",
             "```text",
             f"CONTROL    W1-H P1/P2/P3  delivery order "
             f"{list(CONTROL[3])}",
             f"TREATMENT  W1-J Q1/Q2/Q3  delivery order "
             f"{list(TREATMENT[3])}",
             "```", "",
             "A **cross-pack differential**, not simultaneously randomized "
             "arms: the packs ran at different times. Every other input of the "
             "worker system is pinned.", ""]

    for title, group, order in (("CONTROL — W1-H", control, CONTROL[3]),
                                ("TREATMENT — W1-J", treatment,
                                 TREATMENT[3])):
        lines += [f"## {title}", ""]
        for rec in group:
            lines += [f"### {rec['run']}", ""]
            if rec["status"] != "GRADED":
                lines += [f"- {rec['status']}", ""]
                continue
            lines += ["| row | settles | delivery_position | provenance_slot |"
                      " preservation |",
                      "|---|---|---|---|---|"]
            for pos, row in enumerate(order, start=1):
                lines.append(
                    f"| {row} | {ROW_LABEL[row]} | {pos} | "
                    f"{PROVENANCE_SLOT[row]} | "
                    f"**{rec['rows'][str(row)]}** |")
            lines += ["",
                      f"`preserved_prefix_length` = "
                      f"**{rec['preserved_prefix_length']}** "
                      f"(counted from the start of delivery)", ""]

    lines += ["## Side by side, by delivery position", "",
              "| position | W1-H row | P1 | P2 | P3 | W1-J row | Q1 | Q2 | Q3 |",
              "|---|---|---|---|---|---|---|---|---|"]
    for i in range(len(CONTROL[3])):
        crow, trow = CONTROL[3][i], TREATMENT[3][i]

        def cell(group, row):
            vals = []
            for rec in group:
                if rec["status"] != "GRADED":
                    vals.append("-")
                else:
                    v = rec["rows"][str(row)]
                    vals.append({EXACT_INDIVIDUAL: "EXACT", BUNDLED: "BUND",
                                 NONVERBATIM: "NONVB", ABSENT: "ABS"}[v])
            return vals
        c = cell(control, crow)
        t = cell(treatment, trow)
        lines.append(f"| {i + 1} | {crow} ({ROW_LABEL[crow]}) | "
                     + " | ".join(c) + f" | {trow} ({ROW_LABEL[trow]}) | "
                     + " | ".join(t) + " |")

    lines += ["", "## preserved_prefix_length", "", "```text"]
    for rec in control + treatment:
        if rec["status"] == "GRADED":
            lines.append(f"{rec['pack']} {rec['run']}  "
                         f"{rec['preserved_prefix_length']}")
    lines += ["```", "",
              "**Descriptive.** Three runs per pack. No percentages, no "
              "reliability estimate, and no statistical inference. The "
              "interpretation branches are fixed in `PREREGISTRATION.md` and "
              "are read off the six observations directly.", ""]

    (HERE / "PRESERVATION.md").write_text("\n".join(lines), encoding="utf-8")
    (HERE / "PRESERVATION.json").write_text(
        json.dumps({"control": control, "treatment": treatment,
                    "provenance_slot": PROVENANCE_SLOT}, indent=2),
        encoding="utf-8")
    print("\n".join(lines))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
