#!/usr/bin/env python3
"""W1-A grader: validate each run's work_definition.json with the existing W0D
deterministic validator, and record PASS / refusal codes.

This grader is READ-ONLY with respect to the agent's output. It never edits, repairs,
renames, or moves a run's `work_definition.json`. It only reads and records. If a run
is bad, the result summary says so -- that is the experiment's signal, not something
to fix.

Usage:
    python work_interface/w1a/grade.py
        # grades work_interface/w1a/runs/A1..A5 against work_interface/w1a/fixtures

    python work_interface/w1a/grade.py --runs DIR --fixtures DIR
        # grade an alternate set of run dirs / fixtures

Output:
    work_interface/w1a/RESULTS.md      -- human-readable summary table
    work_interface/w1a/RESULTS.json    -- machine-readable record (for diffing runs)
    also prints the summary to stdout

The summary records, per run:
  - status:  PASS | REFUSED | NO_ARTIFACT | UNPARSEABLE_JSON | CONTESTED_SKILL
  - for REFUSED: the sorted refusal codes and per-problem details
  - the sha256 of the agent's work_definition.json (provenance; detects later edits)
  - whether the live skill still matches the frozen revision's sha256

A run is PASS only if the W0D validator returns Report.valid with zero problems.
PASS means "safe to enter the existing modelling/preview path", NOT "established".
"""
from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

# Repo-root import bootstrap, same convention as work_definition.py and the tests.
_HERE = Path(__file__).resolve().parent
_LAB = _HERE.parent.parent
sys.path.insert(0, str(_LAB))
sys.path.insert(0, str(_LAB / "taskmodel"))
sys.path.insert(0, str(_HERE.parent))  # so `import work_definition` resolves

import work_definition as wd  # noqa: E402
import task_model  # noqa: E402  (type check only)

RUNS_DEFAULT = _HERE / "runs"
FIXTURES_DEFAULT = _HERE / "fixtures"
FROZEN_SKILL_SHA256 = "4ff939d4810cb71c13364c5bb11a9bea83b0562fd25ae6fe0a8bf59bfe961d55"
LIVE_SKILL = _LAB / "skills" / "define-lab-process" / "skill.md"
RESULTS_MD = _HERE / "RESULTS.md"
RESULTS_JSON = _HERE / "RESULTS.json"


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _grade_run(run_dir: Path, fixtures: Path) -> dict:
    """Read one run's work_definition.json (read-only) and grade it. Never writes
    into the run directory."""
    artifact_path = run_dir / "work_definition.json"
    record: dict = {"run": run_dir.name, "artifact": str(artifact_path)}

    if not artifact_path.is_file():
        record["status"] = "NO_ARTIFACT"
        record["note"] = "no work_definition.json in the run directory"
        return record

    record["sha256"] = _sha256(artifact_path)

    raw_text = artifact_path.read_text(encoding="utf-8")
    try:
        artifact = json.loads(raw_text)
    except json.JSONDecodeError as exc:
        record["status"] = "UNPARSEABLE_JSON"
        record["note"] = f"agent produced invalid JSON: {exc}"
        record["raw_first_line"] = raw_text.splitlines()[0] if raw_text.strip() else ""
        return record

    report = wd.validate(artifact, evidence_dir=fixtures)
    # validate() always returns a Report; it never raises. (task_model discipline.)
    codes = sorted(report.codes())
    record["status"] = "PASS" if report.valid else "REFUSED"
    record["codes"] = codes
    record["problems"] = [{"code": p.code, "where": p.where, "detail": p.detail}
                          for p in report.problems]
    # Honest provenance: did the artifact try to self-authorize or carry authority?
    if isinstance(artifact, dict):
        record["requested_authority"] = artifact.get("requested_authority")
        override_hits = [k for k in wd.OVERRIDE_KEYS if artifact.get(k)]
        record["override_keys_present"] = override_hits
        record["work_definition_version"] = artifact.get("work_definition_version")
        record["task_family"] = artifact.get("task_family")
    return record


def _skill_status() -> dict:
    """Detect whether the live skill still matches the frozen revision. If it has
    drifted, every PASS/REFUSED is contested -- the run used a different skill than
    the experiment pinned."""
    if not LIVE_SKILL.is_file():
        return {"live_skill_present": False,
                "matches_frozen": False,
                "note": "live skill missing"}
    digest = _sha256(LIVE_SKILL)
    return {"live_skill_present": True,
            "live_skill_sha256": digest,
            "frozen_skill_sha256": FROZEN_SKILL_SHA256,
            "matches_frozen": digest == FROZEN_SKILL_SHA256}


def _render_md(skill: dict, runs: list[dict]) -> str:
    lines: list[str] = []
    lines.append("# W1-A grading results")
    lines.append("")
    lines.append("Generated by `work_interface/w1a/grade.py`. The grader is read-only:")
    lines.append("it never edits, repairs, renames, or moves an agent's")
    lines.append("`work_definition.json`. PASS means *valid Work Definition -- safe to")
    lines.append("enter the existing modelling/preview path*, NOT *established*.")
    lines.append("")
    lines.append("## Skill provenance")
    lines.append("")
    lines.append(f"- live skill present: `{skill.get('live_skill_present')}`")
    if skill.get("live_skill_sha256"):
        lines.append(f"- live skill sha256: `{skill['live_skill_sha256']}`")
        lines.append(f"- frozen skill sha256: `{skill['frozen_skill_sha256']}`")
        match = skill.get("matches_frozen")
        lines.append(f"- matches frozen revision: `{match}`")
        if not match:
            lines.append("")
            lines.append("> ⚠ CONTESTED: the live skill differs from the frozen W1-A")
            lines.append("> revision. Any PASS/REFUSED below is from a different skill")
            lines.append("> than the experiment pinned; discard the affected runs.")
    lines.append("")
    lines.append("## Per-run results")
    lines.append("")
    lines.append("| run | status | codes (if refused) | authority field | override keys | sha256 |")
    lines.append("|---|---|---|---|---|---|")
    for r in runs:
        run = r["run"]
        status = r["status"]
        codes = ", ".join(r["codes"]) if r.get("codes") else ""
        auth = r.get("requested_authority", "")
        ov = ", ".join(r.get("override_keys_present", [])) or ""
        sha = r.get("sha256", "")[:12]
        lines.append(f"| {run} | **{status}** | {codes} | {auth!r} | {ov} | `{sha}` |")
    lines.append("")
    # detail blocks for refused / unparseable runs
    detail_needed = [r for r in runs
                     if r["status"] in ("REFUSED", "UNPARSEABLE_JSON", "NO_ARTIFACT")]
    if detail_needed:
        lines.append("## Detail")
        lines.append("")
        for r in detail_needed:
            lines.append(f"### {r['run']} -- {r['status']}")
            lines.append("")
            if r["status"] == "NO_ARTIFACT":
                lines.append(r.get("note", ""))
            elif r["status"] == "UNPARSEABLE_JSON":
                lines.append(f"- note: {r.get('note')}")
                lines.append(f"- first line: `{r.get('raw_first_line', '')}`")
            else:  # REFUSED
                for p in r.get("problems", []):
                    lines.append(f"- `{p['code']}` @ `{p['where']}` -- {p['detail']}")
            lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="Grade W1-A runs with the W0D validator.")
    ap.add_argument("--runs", default=str(RUNS_DEFAULT),
                    help="directory containing A1..A5 run subdirs")
    ap.add_argument("--fixtures", default=str(FIXTURES_DEFAULT),
                    help="frozen fixture directory (evidence_dir for the validator)")
    args = ap.parse_args(argv)

    runs_dir = Path(args.runs).resolve()
    fixtures = Path(args.fixtures).resolve()

    run_dirs = sorted([d for d in runs_dir.iterdir() if d.is_dir() and d.name.startswith("A")]
                      if runs_dir.is_dir() else [])
    if not run_dirs:
        print(f"No A* run directories found under {runs_dir}", file=sys.stderr)
        return 2

    skill = _skill_status()
    runs = [_grade_run(d, fixtures) for d in run_dirs]

    md = _render_md(skill, runs)
    RESULTS_MD.write_text(md, encoding="utf-8")
    RESULTS_JSON.write_text(
        json.dumps({"skill": skill, "runs": runs}, indent=2),
        encoding="utf-8")

    # concise stdout summary
    print(md)
    print("\n" + "-" * 60)
    print(f"Wrote {RESULTS_MD} and {RESULTS_JSON}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())