#!/usr/bin/env python3
"""Backlog B-1 — a prep verifier must observe, never mutate.

Several `verify_prep` checks run the pack's own reporters, which write
`RESULTS.*`, `FIDELITY.*`, `AUTHORITY.*` and friends into the pack. On a
**completed** pack that means the verification command rewrites the very
evidence it is verifying:

```text
W1-B / W1-C  results regenerated by a prep run; restored from HEAD
W1-F         flagged in the closure
W1-I         AUTHORITY/RESULTS regenerated twice; restored from 6ce7bd1 both times
W1-J / W1-K  same hazard present, avoided only by not re-running the verifier
```

Bytes were restored every time and no evidence was lost. That is not the point.
**A verifier that mutates what it verifies is the same class of authority defect
this lab exists to design out of workers** -- the shape of a grader repairing the
artifact it grades, or an audit writing into the directory it audits.

Two mechanisms, in order of strength:

```text
refuse_if_executed()   a prep verifier asked to verify a pack that already
                       holds evidence REFUSES. This alone would have prevented
                       every occurrence above.
observational_copy()   checks that genuinely need a reporter's output run it
                       against a temporary COPY, so nothing in the pack is
                       written at all.
```

This module changes **no worker-facing execution semantics**. It constrains only
where verification is allowed to write.
"""
from __future__ import annotations

import hashlib
import shutil
import tempfile
from contextlib import contextmanager
from pathlib import Path

# Files a run directory holds only after it has been executed.
EVIDENCE_NAMES = ("work_definition.json", "acp_transcript.jsonl",
                  "harness_result.json")

# Reporter outputs a pack holds only after it has been graded.
REPORT_NAMES = ("RESULTS.md", "RESULTS.json", "FIDELITY.md", "FIDELITY.json",
                "AUTHORITY.md", "AUTHORITY.json", "TOKENIZATION.md",
                "TOKENIZATION.json", "SURFACE_C.md", "SURFACE_C.json",
                "PRESERVATION.md", "PRESERVATION.json", "BASELINE.md",
                "BASELINE.json")


class PackAlreadyExecuted(RuntimeError):
    """Raised instead of silently rewriting a completed pack's evidence."""


def executed_runs(pack_dir: Path, runs: list[str]) -> list[str]:
    out = []
    for run in runs:
        d = Path(pack_dir) / "runs" / run
        if any((d / n).exists() for n in EVIDENCE_NAMES):
            out.append(run)
    return out


def refuse_if_executed(pack_dir: Path, runs: list[str]) -> None:
    """The primary guard. A prep verifier has no business touching a used pack."""
    used = executed_runs(pack_dir, runs)
    if used:
        raise PackAlreadyExecuted(
            f"{Path(pack_dir).name} has already been executed "
            f"({', '.join(used)} hold evidence).\n"
            f"verify_prep is a PRE-run check and would regenerate reporter "
            f"outputs over frozen evidence. Refusing.\n"
            f"To inspect a completed pack, read its reporter outputs, or run "
            f"the reporters yourself and compare -- do not run verify_prep.")


@contextmanager
def observational_copy(pack_dir: Path):
    """Yield a temp copy of the pack. The original is never written to.

    For checks that must actually invoke a reporter (e.g. "the grader returns
    NO_ARTIFACT on empty runs"). Anything the reporter writes lands in the copy
    and is discarded.
    """
    pack_dir = Path(pack_dir)
    tmp = Path(tempfile.mkdtemp(prefix=f"prep_{pack_dir.name}_"))
    dest = tmp / pack_dir.name
    shutil.copytree(pack_dir, dest,
                    ignore=shutil.ignore_patterns("__pycache__"))
    try:
        yield dest
    finally:
        shutil.rmtree(tmp, ignore_errors=True)


def fingerprint(pack_dir: Path) -> dict[str, str]:
    """sha256 of every tracked-looking file, for proving nothing was written."""
    out: dict[str, str] = {}
    for p in sorted(Path(pack_dir).rglob("*")):
        if p.is_file() and "__pycache__" not in p.parts:
            rel = str(p.relative_to(pack_dir)).replace("\\", "/")
            out[rel] = hashlib.sha256(p.read_bytes()).hexdigest()
    return out


def assert_unchanged(before: dict[str, str], after: dict[str, str]) -> list[str]:
    """Return a list of mutations. Empty means the verifier stayed read-only."""
    problems = []
    for k in sorted(set(before) | set(after)):
        b, a = before.get(k), after.get(k)
        if b is None:
            problems.append(f"CREATED {k}")
        elif a is None:
            problems.append(f"DELETED {k}")
        elif a != b:
            problems.append(f"MODIFIED {k}")
    return problems
